### ISSUE TITLE
1.4.5 is a breaking change

### ISSUE THREAD

**Issue by m90** [alicoding/node-transifex#14]
When updating from 1.4.4 to 1.4.5 breaking changes to the interface of the module were introduced as the additional argument has been inserted before the callback: https://github.com/alicoding/node-transifex/compare/v1.4.4...v1.4.5#diff-6c2c6bafbcd7b4bd1e1cf6aecab7604dR461

Everyone relying on the old method signature will now get `callback is not a function`.

While I see the reason behind the change it'd be cool if we could get a backwards compatible release at 1.4.6 and release the breaking changes as 2.0.0

**Comment by alicoding** [comment]
Thanks for reporting this issue @m90 I will see what I can do ASAP

@mattkime do you have time to help on this?

**Comment by mattkime** [comment]
https://github.com/alicoding/node-transifex/commit/4b8ff5b8c4292d9f0d701104de167e70195f848e looks like the offending commit

@pmoons

**Comment by mattkime** [comment]
actually, i should verify that my theory is accurate. 

@m90 - would this fix your problem?

**Comment by m90** [comment]
I fixed my issues by locking things to 1.4.4 already, so I can confirm that this is the root cause of the issue. Rolling back in 1.4.6 would fix things for me, but then it will probably break things for people relying on 1.4.5's Interface. Don't know of a good solution.

Thanks for tackling this so quickly in any case.
